### ISSUE TITLE
Error is thrown at npm run dev

### ISSUE THREAD

**Issue by ns23** [leftstick/generator-electron-naive#2]
`

youtube-downloader@1.0.0 dev /vagrant/youtube-downloader
> node ./node_modules/.bin/gulp dev

[06:52:22] Using gulpfile /vagrant/youtube-downloader/gulpfile.js
[06:52:22] Starting 'dev'...
[06:52:23] 'dev' errored after 1.17 s
[06:52:23] Error: Command failed: node ./node_modules/.bin/electron ./src/

    at ChildProcess.exithandler (child_process.js:270:12)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:921:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
`[](url)``

**Comment by leftstick** [comment]
I just tried, it's working. Can you provide more error information?

**Comment by ns23** [comment]
I am using vagrant for development.
OS is Ubuntu 14.04.
If i run `node ./node_modules/.bin/electron ./src/` in terminal it runs successfully. but with  ` npm run dev`
it fails..
I have attached gulpfile.js .
If you need any more information .please let me know
[gulpfile.txt](https://github.com/leftstick/generator-electron-naive/files/1187322/gulpfile.txt)

**Comment by leftstick** [comment]
That's weird!   What is the version of node.js you are using?

**Comment by ns23** [comment]
I am using node  v8.2.1

**Comment by leftstick** [comment]
As described in `npm` doc [run-script](https://docs.npmjs.com/cli/run-script), see below:

![screen shot 2017-08-02 at 4 02 39 pm](https://user-images.githubusercontent.com/1059956/28863568-0be996d6-779c-11e7-805c-e8087020b683.png)

`npm run dev` is equivalent to `node_modules/.bin/gulp dev`. What is the error? Caused by `gulpfile.js`? Please provide full error message

**Comment by ns23** [comment]
![error](https://user-images.githubusercontent.com/10084011/28960072-d3f5c792-791a-11e7-8408-5663f16b76fb.png)

i created new project named naive and then ran npm run dev command..i got error as shown in the image.
Do you want me to lower node version to 6(stable) and check if its giving error on my system?
 
[gulpfile.txt](https://github.com/leftstick/generator-electron-naive/files/1199661/gulpfile.txt)
[package.txt](https://github.com/leftstick/generator-electron-naive/files/1199662/package.txt)

**Comment by leftstick** [comment]
@ns23  can you try `node ./node_modules/.bin/electron ./src/` in CLI to see if this command working? I don't have a ubuntu env, need your help for confirming this issue

**Comment by ns23** [comment]
coomand is executed successfully...window appers ..but when i press alt + tab,window disappears

![error_log-2017-08-04_14 30](https://user-images.githubusercontent.com/10084011/28962430-52eff542-7923-11e7-996b-25d79b9ffb21.gif)
